### ISSUE TITLE
the game is running SOOOO BAD commpaere to last version

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#13]
Runs worse than 19 maybe remove some of the building mods they take a lot of ram

game hard crashed as without a log nor booting me back to the launcher. takes excessive ram. even when optimizing the games settings, game still ran poorly. lag was a non issue, however items not loading, or dynamic lighting not functioning is the main issues

**Comment by uthw** [comment]
Every time the game opens it makes a log so just send me a zip of your entire logs folder and ill look for potential issues. Yes, even when it hard crashes without going back to the launcher (speaking from experience)

I don't know how much I can do about performance but like i said in call removing the "entity culling" mod and turning off rubidium's entity culling increased your fps in version 17 or 18. This is because entity culling basically does path tracing to determine if an entity is behind you, which is a CPU heavy process and can lower FPS by quite a lot with an IGPU. I would also appreciate if you sent me a spark log (run `/spark profiler`, wait around a minute, then run `spark profiler stop` so I can see what the most TPS heavy processes are.

Can you send me your `options.txt` so I can see how you optimized your settings?

Idk what you mean by "items not loading", can you elaborate on that?

In the next version, dynamic lights will be disabled since it breaks with the newest version of Rubidium regardless.

**Comment by uthw** [comment]
Overall opinion from both of us seems to be v21 fixed whatever v20's performance issue was
