### ISSUE TITLE
base game Bee hives are hard if not impossible to find

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#42]
This could be fixed with a crafting recipe most likely since you can still harvest the modded bee hives. _im pretty sure_

**Comment by uthw** [comment]
Bee nests generate, but are a lot more rare on terraforged because it generates trees differently. They are more common in places with a lot of flowers.

I fixed this regardless, my stupid ass power keeps going out (along with my wifi) so i have to comment on my phone.

There is an item called the bee locator (something along those lines) from Productive Bees that is basically a compass for beehives. This is already in the quests but not getting started.

On 0.21.2 you have to actually interact with the beehive you want to find, but on the next minor release this item will be bound to vanilla bee nests when it's crafted.

**Comment by Guineapigboyx** [comment]
That is perfect I did not even know the bee track was thing.

**Comment by uthw** [comment]
Recipe added in [d6b3b6a](https://github.com/uthw/minecraft-modpack/commit/d6b3b6a5c6835461465626fc0af9384e935c7b2d)
